version: "2.2"

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    volumes:
      - ./mongo:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456

  redis:
    image: redis
    container_name: redis
    restart: always
    volumes:
      - ./redis/redis-data:/var/lib/redis
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
    command: redis-server --requirepass 123456

  mysql:
    image: mysql:5.5
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/db_data:/var/lib/mysql
      - ./mysql/:/file-manager
    environment:
      MYSQL_ROOT_PASSWORD: 123456 #
      MYSQL_DATABASE: filemanager
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456

  mssql:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: mssql
    environment:
      SA_PASSWORD: bw@123456
      ACCEPT_EULA: Y
    volumes:
      - ./mssql/db_data:/var/opt/mssql/data
      - ./mssql/bk:/var/opt/mssql/backup
    ports:
      - "1433:1433"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.1
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=elasticsearch
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:7.13.1
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    networks:
      - elastic

networks:
  elastic:
    driver: bridge
