version: "2.2"

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    volumes:
      - ./mongo:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456

  redis:
    image: redis
    container_name: redis
    restart: always
    volumes:
      - ./redis/redis-data:/var/lib/redis
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
    command: redis-server --requirepass 123456
